// src/components/Age.tsx
import { useState, useEffect } from "react";

function getAge() {
	return (
		(new Date().getTime() - new Date(2002, 0, 9).getTime()) /
		(1000 * 60 * 60 * 24 * 365.25)
	)
		.toString()
		.slice(0, 12);
}

export const Age = () => {
	const [age, setAge] = useState(getAge());

	useEffect(() => {
		const interval = setInterval(() => {
			setAge(getAge());
		});
		return () => {
			clearInterval(interval);
		};
	}, []);

	return <span className="font-mono">{age}</span>;
};

// src/components/Age.svelte
<script>
  let age = "00.000000000";
  const birthday = new Date(2002, 0, 9).getTime();
  const getAge = () => {
    age = ((new Date().getTime() - birthday) / 31557600000)
      .toString()
      .slice(0, 12);
  };

  let interval;

  $: {
    clearInterval(interval);
    interval = setInterval(getAge, 50);
  }
</script>

<span class="font-mono">{age}</span>
