// src/components/Post.svelte
<script lang="ts">
  import type { CollectionEntry } from "astro:content";

  export let post: CollectionEntry<"blog">;

  const dateString = new Date(post.data.pubDate).toLocaleDateString("en-us", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
</script>

<a
  href={`/blog/${post.slug}`}
  rel="prefetch"
  class="flex flex-col gap-y-3 rounded-xl p-4 transition-colors hover:bg-neutral-800 hover:no-underline"
>
  <h3 class="text-themeAccent text-xl font-extrabold md:text-2xl">
    {post.data.title}
  </h3>
  <p class="text-sm font-medium md:text-base">{post.data.description}</p>
  <div
    class="flex items-center gap-x-2 text-xs font-medium text-neutral-200 md:text-sm"
  >
    <time datetime={post.data.pubDate}> {dateString} </time>
    <span>•</span>
    <span>{post.data.readingTime}</span>
  </div>
</a>

// src/components/Post.tsx
import { type CollectionEntry } from "astro:content";
type PostType = CollectionEntry<"blog">;

export const Post = ({ data: post }: { data: PostType }) => {
  return (
    <a
      href={`/blog/${post.slug}`}
      rel="prefetch"
      className="flex flex-col gap-y-3 hover:(no-underline bg-neutral-800) p-4 mb-8 transition-colors rounded-xl"
    >
      <h3 className="text-(themeAccent xl) md:text-2xl font-extrabold">
        {post.data.title}
      </h3>

      <p className="text-sm md:text-base font-medium">
        {post.data.description}
      </p>

      <div className="flex items-center gap-x-2 text-(neutral-200 xs) md:text-sm font-medium">
        <time dateTime={post.data.pubDate}>
          {new Date(post.data.pubDate).toLocaleDateString("en-us", {
            year: "numeric",
            month: "short",
            day: "numeric",
          })}
        </time>

        <span>•</span>

        <span>{post.data.readingTime}</span>
      </div>
    </a>
  );
};
